disabled = false
languageCode = "en"
languageName = "English"
title = "Tiwza"
weight = 1

[params]
dateFormat = "2 January 2006"
displayName = "EN"
isoCode = "en"
logo = "static/img/logo.png"
rtl = false
# secondaryLogo = "img/secondary-logo.png"
copyright = "Copy, _right?_ :thinking_face:"
description = "ĐÂY LÀ NƠI LƯU NHỮNG GÌ MÌNH ĐÃ LÀM ĐƯỢC TRONG ATTT"

# Uncomment và điền thông tin author nếu cần
[params.author]
bio = "A little bit about you"
email = "youremail@example.com"
headline = "I'm only human"
image = "img/logo.png"
imageQuality = 96
name = "Your name here"

# Social links - uncomment và thay thế bằng links thực tế
[[params.author.links]]
youtube = "https://www.youtube.com/@TungPhan-qf4tu"

# Các social links khác (uncomment khi cần)
# [[params.author.links]]
# github = "https://github.com/username"

# [[params.author.links]]
# linkedin = "https://linkedin.com/in/username"

# [[params.author.links]]
# twitter = "https://twitter.com/username"

# [[params.author.links]]
# instagram = "https://instagram.com/username"

[[params.author.links]]
youtube = "https://www.youtube.com/@TungPhan-qf4tu"

# Thêm các links khác theo format:
# [[params.author.links]]
# platform_name = "url"
