# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters

autoSwitchAppearance = true 
colorScheme = "blowfish" 
defaultAppearance = "light" # valid options: light or dark

enableCodeCopy = false
enableSearch = true

replyByEmail = false

# mainSections = ["section1", "section2"]
# robots = ""

disableImageOptimization = false
disableImageOptimizationMD = false
disableTextInHeader = false
# backgroundImageWidth = 1200

# defaultBackgroundImage = "IMAGE.jpg" # used as default for background images 
# defaultFeaturedImage = "IMAGE.jpg" # used as default for featured images in all articles
# defaultSocialImage = "/android-chrome-512x512.png" # used as default for social media sharing (Open Graph and Twitter)

# highlightCurrentMenuArea = true
# smartTOC = true
# smartTOCHideUnfocusedChildren = true

fingerprintAlgorithm = "sha512" # Valid values are "sha512" (default), "sha384", "sha256"

forgejoDefaultServer = "https://v8.next.forgejo.org"
giteaDefaultServer = "https://git.fsfe.org"

[header]
layout = "basic" # valid options: basic, fixed, fixed-fill, fixed-gradient, fixed-fill-blur

[footer]
showAppearanceSwitcher = true
showCopyright = true
showMenu = true
showScrollToTop = true
showThemeAttribution = true

[homepage]
layout = "profile" # valid options: page, profile, hero, card, background, custom
#homepageImage = "IMAGE.jpg" # used in: hero, and card
cardView = false 
cardViewScreenWidth = false 
disableHeroImageFilter = false # only used when layout equals hero
layoutBackgroundBlur = false # only used when layout equals background
showMoreLink = false 
showMoreLinkDest = "/posts/" 
showRecent = false 
showRecentItems = 5 

[article]
showAuthor = true
showDate = true
showDateOnlyInArticle = false
showDateUpdated = false
showLikes = false
showViews = false
# showAuthorBottom = false
showHero = false
# heroStyle = "basic" # valid options: basic, big, background, thumbAndBackground
layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
showBreadcrumbs = false 
showDraftLabel = true 
showEdit = false 
# editURL = "https://github.com/username/repo/"
editAppendPath = true
invertPagination = false
seriesOpened = false
showHeadingAnchors = true
showPagination = true
showReadingTime = true
showTableOfContents = false
# showRelatedContent = false
# relatedContentLimit = 3
showAuthorsBadges = false 
showCategoryOnly = false # use showTaxonomies OR showCategoryOnly, not both
showTaxonomies = false # use showTaxonomies OR showCategoryOnly, not both
showWordCount = true 
# sharingLinks = [ "linkedin", "twitter", "bluesky", "mastodon", "reddit", "pinterest", "facebook", "email", "whatsapp", "telegram", "line"]
showZenMode = false

[list]
showHero = false
# heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
cardView = false 
cardViewScreenWidth = false 
constrainItemsWidth = false 
groupByYear = true 
layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
orderByWeight = false 
showBreadcrumbs = false 
showCards = false 
showLikes = false 
showSummary = false 
showTableOfContents = false 
showViews = false 

[sitemap]
excludedKinds = ["taxonomy", "term"]

[taxonomy]
showHero = false
showTermCount = true
# heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
cardView = false
showBreadcrumbs = false
showLikes = false
showTableOfContents = false
showViews = false

[term]
showHero = false
# heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
cardView = false
cardViewScreenWidth = false
groupByYear = false
showBreadcrumbs = false
showLikes = false
showTableOfContents = true
showViews = false

[firebase]
# apiKey = "XXXXXX"
# authDomain = "XXXXXX"
# projectId = "XXXXXX"
# storageBucket = "XXXXXX"
# messagingSenderId = "XXXXXX"
# appId = "XXXXXX"
# measurementId = "XXXXXX"

[fathomAnalytics]
# site = "ABC12345"
# domain = "llama.yoursite.com"

[umamiAnalytics]
# websiteid = "ABC12345"
# domain = "llama.yoursite.com"
# dataDomains = "yoursite.com,yoursite2.com"
# scriptName = ""
# enableTrackEvent = true

[selineAnalytics]
# token = "XXXXXX"
# enableTrackEvent = true

[buymeacoffee]
# identifier = ""
# globalWidget = true
# globalWidgetMessage = "Hello"
# globalWidgetColor = "#FFDD00"
# globalWidgetPosition = "Right"

[verification]
# google = ""
# bing = ""
# pinterest = ""
# yandex = ""
# fediverse = ""

[rssnext]
# feedId = ""
# userId = ""

[advertisement]
# adsense = ""
